auctions/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name="auctions"

urlpatterns = [

    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("add_listing", views.add_listing, name="add_listing"),
    path("<int:listing_id>", views.listing_page, name="listing_page"),
    path("<int:listing_id>/update_watchlist", views.add_to_watchlist, name="addtowatchlist"),
    path("watchlist", views.watchlist_page, name="watchlist"),
    path("<int:listing_id>/update_status", views.close_listing, name="close_listing"),
    path("categories", views.get_categories, name="categories"),
    path("<str:category>", views.get_category_listings, name="get_category_listings"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.validators import URLValidator
from django.db import models
from crum import get_current_user
from django.conf import settings
import datetime



class User(AbstractUser):
    pass


class Auction(models.Model):
    class ProductCategory(models.TextChoices):
        App_Acc = 'AA', _('Apparel and Accessories')
        Sty_Fash = 'SF', _('Style and Fashion')
        Hom_Gar = 'HG', _('Home and Garden')
        Spor_Goo = 'SG', _('Sporting and Goods')
        Health_Well = 'HW', _('Health and Wellness')
        Child_Infan = 'CI', _('Children and Infants')
        Electronic = 'EG', _('Electronic Goods')
        Home = 'HO', _('Home')
        Auto = 'AU', _('Automotive')
        Oth_Cat = 'OC', _('Other Categories')
        Not_Kwn = 'NK', _('Not Known')

    class ListingStatus(models.TextChoices):
        active = 'ac', _("Active")
        closed = 'cl', _("Closed")

    product_cat = models.CharField(max_length=2, choices=ProductCategory.choices, default=ProductCategory.Not_Kwn,)
    listing_status = models.CharField(max_length=2, choices=ListingStatus.choices, default=ListingStatus.active,)
    product_name = models.CharField(max_length=64)
    minimal_bid = models.DecimalField(max_digits=19, decimal_places=2)
    description =  models.TextField(blank=True)
    product_image_url = models.URLField(max_length=250, blank=True, validators=[URLValidator()])
    category_image_url = models.URLField(max_length=250, blank=True, validators=[URLValidator()])
    pubdate = models.DateTimeField(auto_now_add=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, default=get_current_user, on_delete=models.CASCADE, blank=True, related_name="listings")
    

    def __str__(self):
        return f"{self.id}: {self.product_name}, Starting bid: {self.minimal_bid}, Status:{self.listing_status}, category: {self.product_cat}"


    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.created_by = user
        self.modified_by = user
        super(Auction, self).save(*args, **kwargs)

class Bid(models.Model):
    Product_Name = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="active_bids")
    Amount = models.DecimalField(max_digits=19, decimal_places=2)
    BidDate = models.DateTimeField(auto_now_add=True, blank=True)
    BidAuthor = models.ForeignKey(settings.AUTH_USER_MODEL, default=get_current_user, on_delete=models.CASCADE, blank=True, related_name="bids")

    def __str__(self):
        return f"{self.Product_Name} {self.Amount} {self.BidAuthor} {self.BidDate}"

    
    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.created_by = user
        self.modified_by = user
        super(Bid, self).save(*args, **kwargs)


class WatchList(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, default=get_current_user, on_delete=models.CASCADE, blank=True, related_name="followed_listings")
    Product_Name = models.ForeignKey(Auction, on_delete=models.CASCADE, blank=True, related_name="likes")
    added_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return f"{self.Product_Name}, {self.added_at}"


class Comment(models.Model):
    made_by =  models.ForeignKey(settings.AUTH_USER_MODEL, default=get_current_user, on_delete=models.CASCADE, blank=True, related_name="comments")
    Product_Name = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="Comments")
    title = models.CharField(max_length=200)
    Comment_Date = models.DateTimeField(blank=True, default=timezone.localtime)
    Content = models.TextField(blank=True)

    def __str__(self):
            return f"{self.title}: \n {self.Content}"

auctions/forms.py
from django import forms
from django.db.models import Max

from .models import Auction, Bid, Comment



class NewListingForm(forms.ModelForm):
    class Meta:
        model = Auction
        exclude = ('author', 'listing_status')

        labels = {
             "product_name": "Listing Title",
             "product_cat": "Listing category",
             "minimal_bid": "Starting Bid",
             "description": "Description",
             "product_image_url": "Listing Image URL",
             "category_image_url": "Listing Category Image URL"
             }
        
        widgets = {
            "product_name": forms.TextInput(attrs={'class': 'form-control'}),
            "product_cat": forms.Select( attrs={'class': 'form-control'}),
            "minimal_bid": forms.NumberInput(attrs={'class': 'form-control'}),
            "description":  forms.Textarea(attrs={'class': 'form-control'}),
            "product_image_url": forms.URLInput(attrs={'class': 'form-control'}),
            "category_image_url": forms.URLInput(attrs={'class': 'form-control'})
        }
        

class NewBidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ('Amount', 'Product_Name')

        labels = {
        'Amount': '',
    }

        widgets = {
            "Amount": forms.NumberInput(attrs={'class': 'form-control'}),
            "Product_Name": forms.HiddenInput(),
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        listing_id = self.cleaned_data['Product_Name'].id
        amount = cleaned_data.get('Amount')
        starting_bid = cleaned_data.get('Product_Name').minimal_bid
        bids = Bid.objects.filter(Product_Name=listing_id)
        max_bid = bids.aggregate(Max('Amount'))['Amount__max']
        if not max_bid:
            if amount < starting_bid:
                raise forms.ValidationError('Bid amount must be greater or equal than the starting bid')
            return self.cleaned_data
        else:
            if amount < starting_bid or amount <= max_bid:
                raise forms.ValidationError('Bid must be 1: \n greater or equal than the starting bid, \n 2: greater than the current highest bid')
            return self.cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

        labels = {
             "title": "Comment Title",
             "Content": "Content"
             }
        
        widgets = {
            "title": forms.TextInput(attrs={'class': 'form-control'}),
            "Content":  forms.Textarea(attrs={'class': 'form-control'}),
             "Product_Name": forms.HiddenInput(),
             "made_by": forms.HiddenInput(),
             "Comment_Date": forms.HiddenInput()
            }

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import Max, Count
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib import messages
from django import forms
import random

from .forms import NewListingForm, NewBidForm, CommentForm
from .models import User, Auction, WatchList, Bid, Comment



def index(request):
    trendings = sorted(Auction.objects.annotate(num_bids=Count('active_bids')).order_by('-num_bids')[:8], key=lambda x: random.random())

    return render(request, "auctions/index.html", {
        "listings": Auction.objects.all(),
        "trendings": trendings
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@login_required
def add_listing(request):
    if request.method == "POST":
        form = NewListingForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("auctions:index"))
    return render(request, "auctions/add_listing.html", {
        "form": NewListingForm()
    })

@login_required
def listing_page(request, listing_id):
    watched_by_user = WatchList.objects.filter(author=request.user, Product_Name_id=listing_id)
    page = Auction.objects.get(pk=listing_id)
    listing_author = page.author
    bids = Bid.objects.filter(Product_Name=listing_id)
    comments = Comment.objects.filter(Product_Name=listing_id)
    n_comments = len(comments)

    if len(bids) == 0:
        max_bid = "No Bid has been made yet on this Listing"
        winner = False
    else:
        max_bid = bids.aggregate(Max('Amount'))['Amount__max']
        winner_id = Bid.objects.filter(Amount=max_bid).values('BidAuthor')[0]['BidAuthor']
        winner = User.objects.get(pk=winner_id)

    bidform = NewBidForm(initial = {
        "Product_Name": page,
        "BidAuthor": request.user
    })

    commentform = CommentForm(initial = {
        "Product_Name": page,
        "made_by": request.user
    })

    if len(watched_by_user) == 0:
        watch_button_name = " Add to watchlist"
        icon_color = " color: Grey;"
    else:
        watch_button_name = "  Remove from watchlist"
        icon_color = "Dodgerblue"

    if page.listing_status == 'cl':
        close_button_status = "disabled"
        close_button_class = "not-allowed"
        close_button_text = "Auction is closed"
        
        if winner == request.user:
            display_winner = True
        else:
            display_winner = False
    else:
        close_button_status = ""
        close_button_class = ""
        close_button_text = "Close Auction"
        display_winner = False

    if page.author != request.user:
        show_close_button = False
    else:
        show_close_button = True
    
    if request.method == "GET":
        if page is not None:
            return render(request, "auctions/listing_page.html", {
                "page": page,
                "max_bid": max_bid,
                "winner": winner,
                "display_winner": display_winner,
                "button_name": watch_button_name,
                "button_status": close_button_status,
                "button_class": close_button_class,
                "close_button_text": close_button_text,
                "show_button": show_close_button,
                "icon_color": icon_color,
                "bidform": bidform, 
                "commentform": commentform,
                "comments": comments,
                "n_comments": n_comments
            })

    if request.method == "POST" and 'bid' in request.POST:
        
        if listing_author != request.user:
            bidform = NewBidForm(request.POST or None)
            
            if bidform.is_valid():
                bidform.save()
                return redirect('auctions:listing_page', listing_id)
        else:
            messages.warning(request, "You cannot bid  on your own listing!")
            return redirect('auctions:listing_page', listing_id)

    elif request.method == "POST" and 'comment' in request.POST:

        commentform = CommentForm(request.POST or None)
            
        if commentform.is_valid():
            commentform.save()
            return redirect('auctions:listing_page', listing_id)
        else:
            messages.warning(request,'Form is not valid!')
            return redirect('auctions:listing_page', listing_id)
        
    return render(request, "auctions/listing_page.html", {
                "page": page,
                "bidform": bidform,
                "commentform": commentform
            })


@login_required
def add_to_watchlist(request, listing_id):
    if request.method == "POST":
        page = get_object_or_404(Auction, pk=listing_id)
        if page.author != request.user:
            new_watch, created = WatchList.objects.get_or_create(author=request.user, Product_Name_id=listing_id)
            if not created:
                watched = WatchList.objects.get(author=request.user, Product_Name_id=listing_id)
                watched.delete()
                #messages.warning(request,'The item has been removed successfully!')
                return redirect('auctions:listing_page', listing_id)
            else:
                #messages.success(request,'The item was added to your watchlist!')
                return redirect('auctions:listing_page', listing_id)
        else:
            messages.warning(request, "Cannot add your own listing to your watchlist!")
            return redirect('auctions:listing_page', listing_id)


@login_required
def watchlist_page(request):
    watched_list = WatchList.objects.filter(author=request.user)
    nb_items = len(watched_list)
    
    if request.method == "GET":
        if nb_items == 0:
            no_item = True
        else:
            no_item = False

        return render(request, "auctions/watchlist.html", {
            "watched_list": watched_list,
            "no_item": no_item
        })



@login_required
def close_listing(request, listing_id):
    if request.method == "POST":
        page = Auction.objects.get(pk=listing_id)
        if page.author == request.user:
            page.listing_status = 'cl'
            page.save()
            return redirect('auctions:listing_page', listing_id)
        else:
            messages.error(request, "here we go again!")
            return redirect('auctions:listing_page', listing_id)

                   
@login_required
def get_categories(request):
    listings = Auction.objects.annotate(num_bids=Count('active_bids')).order_by('num_bids')[:8]
    labs = dict(Auction.ProductCategory.choices)
    
    categories = Auction.objects.order_by('product_cat').values("product_cat", 'category_image_url').distinct()
    
    categories = [{k: labs.get(v, v) for k, v in categories[i].items()}  for i in range(len(categories))]

    if request.method == 'GET':
        return render(request, 'auctions/categories.html', {
            "categories": categories,
            "listings": listings
        })


@login_required
def get_category_listings(request, category):
    if request.method == 'GET':
        labs = dict(Auction.ProductCategory.choices)
        try:
            category = [k for k, v in labs.items() if category == v][0]
        except IndexError:
            category = None

        listings = Auction.objects.filter(product_cat=category)

        return render(request, "auctions/category_listings.html", {
        "listings": listings
        })

auctions/templates/auctions/add_listing.html
{% extends "auctions/layout.html" %}

{% block body %}
<h3>Create a new listing</h3>
<div class="col-6">
<div class="form-group">
<form action="{% url 'auctions:add_listing' %}" method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <div class="row">
        <div class="col-12">
        <button type="submit" class="btn btn-primary float-right">Create
</button>
        </div>
    </div>
</form>
</div>
</div>
{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}
{% load auctions_extra %}

{% block body %}
<h3 class="text-center">Categories</h3>
<hr> <br>
<div class="categories">
  <section class="products-cat">
    {% for category in categories %}
    <div class="card mr-3 mb-3" style="width: 18rem;">
      <a href="{% url 'auctions:get_category_listings' category.product_cat %}">
      <img class="card-img-top" src="{{category.category_image_url}}" alt="Image not available">
    </a>
      <div class="card-body">
        <h5 class="card-title">
          <a href="{% url 'auctions:get_category_listings' category.product_cat %}">{{category.product_cat}}
          </a>
        </h5>
      </div>
    </div>
    {% endfor %}
  </section>
</div>

  {% endblock %}

auctions/templates/auctions/category_listings.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h3>Listings</h3><hr> <br>
    <section class="products">
    {% for listing in listings %}
        <div class="card mr-3 mb-3" style="width: 18rem;">
          <a href="{% url 'auctions:listing_page' listing_id=listing.id%}">
          <img class="card-img-top" src="{{listing.product_image_url}}" alt="Image not available">
          </a>
          <div class="card-body">
            <h5 class="card-title">
              <a href="{% url 'auctions:listing_page' listing_id=listing.id%}">{{listing.product_name}}
              </a> 
            </h5>
            <p>Starting bid: {{listing.minimal_bid}} €</p>
            <p class="card-text">{{listing.description}}.</p>
            <p>Created at: {{listing.pubdate}}</p>
            <a href="{% url 'auctions:listing_page' listing_id=listing.id%}" class="btn btn-outline-secondary" style="position: absolute; bottom: 0; right: 0;">
              Show details
            </a>
          </div>
        </div>
      {% endfor %}
      </section>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% block title %}Auctions{% endblock %}
        </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <script type='text/javascript' src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    </head>
    <body>
        
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'auctions:index' %}">Auctions</a>
            <div class="collapse navbar-collapse justify-content-end" >
              <div class="navbar-nav">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'auctions:add_listing' %}">Create a listing</a>
                <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist
    
                        <span class="badge badge-primary" > {{ nb_items }} </span>

                </a>
                <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
            {% else %}
                <a class="nav-link mr-auto" href="{% url 'auctions:login' %}">Log In</a>
                <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
            {% endif %} 
            </div>
            </div>
          </nav>

            <p style="text-align: right;">
            {% if user.is_authenticated %}
                Signed in as <strong>{{user.username|title}}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
            </p>
        <hr>
            {% block body %} 
            {% endblock %}
        <script src="{% static 'auctions/js/toggle_comment.js' %}"></script>
    </body>
</html>

auctions/templates/auctions/listing_page.html
{% extends "auctions/layout.html" %}


{% block body %}
<div class="container ">
    <div class="row" style="box-shadow: 0 -1px 6px 1px rgba(0,0,0,0.1);">
        <div class="col-6">
        <div class="image">
            <div class="overlay">
                <form action="{% url 'auctions:addtowatchlist' listing_id=page.id%}" method="post">
                    {% csrf_token %}
                    <button type="submit" name="Add"  class="btn btn-light pull-right" data-toggle="tooltip" data-placement="right" title="{{button_name}}">  
                        <span style="color:{{icon_color}};">
                            <i class="fa fa-heart" aria-hidden="true"></i> 
                        </span>
                    </button>
                </form> 
            </div>
            <img src="{{page.product_image_url}}" class="card-img-top2 rounded">
          </div>
        </div>
        <div class="col-6" style="position: relative;" >
          
            <div >
                <h4>{{page.product_name}}</h4> 
                <br>
                <p><strong>Description: </strong>{{page.description}}</p>
                <p><strong>Initial Price: </strong><span>{{page.minimal_bid}} €</span></p>
                {% if display_winner%}
                <p><strong>Congratulations {{winner}}! </strong> You won the Bid</p> 
                {% else %}
                <p><strong>Current Highest Bid: </strong>{{max_bid}}€</p> 
                {% endif %} 
            </div>
            <br>
            <div style="bottom: 0;">
                <h5>Details</h5>
                <ul >
                    <li><strong>Listed By</strong>: {{page.author|title}}</li>
                    <li><strong>Publication Date</strong> : {{page.pubdate}}</li>
                    <li><strong>Category</strong>: {{page.get_product_cat_display|title}}</li>
                    <li><strong>Status</strong>: {{page.get_listing_status_display|title}}</li>
                </ul>  
            </div>
                <div class="form-group">
                    <form action="{% url 'auctions:listing_page' listing_id=page.id%}" method="post">
                        {% csrf_token %}
                        {{ bidform}}
                        <div class="border border-light p-3 mb-4 text-center">
                            <button type="submit" name="bid" class="btn btn-primary {{button_class}}" {{button_status}}>Submit your Bid</button>
                        </div>
                    </form>
                </div>
        </div>
            <br>
            {% if show_button %}
            <div  style="position: absolute; right: 0;" >
                <form action="{% url 'auctions:close_listing' listing_id=page.id%}" method="post">
                    {% csrf_token %}
                <button type="submit" name="Close"  class="btn btn-outline {{button_class}}" {{button_status}} >
                    <span>
                        <i class="fa fa-lock" aria-hidden="true"></i> 
                    </span>
                    {{close_button_text}}
                </button>
                </form>
            </div>
            {% endif %}
            <div>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <script>alert("{{ message }}")</script> 
                    {% endfor %}
                </ul>
                {% endif %}
            </div>                             
        
</div>

<section class="content-item" id="comments">
    <div class="container">  
        <div class="row">
            <div class="col-sm-8">
                <button type="button" id="comment" class="btn btn-outline-link active" onclick="$().button('toggle')">Add a new comment  
                    <span style="color: rgb(12, 11, 11); size: 20px; font-weight: bold;">
                        <i class="fa fa-angle-down" aria-hidden="true"></i>
                    </span>
                </button>
                
                <div class="commentform">
                <form action="{% url 'auctions:listing_page' listing_id=page.id%}" method="post">
                    {% csrf_token %}
                    {{commentform}}
                    <div class="border border-light p-3 mb-4 text-center">
                        <button type="submit" name="comment" class="btn btn-normal pull-right" >Submit Comment</button>
                    </div>
                </form>
                </div>

                {% if n_comments > 0%}
                <h3 style="margin-top: 20px;">{{n_comments}} Comments</h3>
                {% else %}
                <h3 style="margin-top: 20px;">No Comment has been made yet</h3>
                {% endif %}

                {% for comment in comments %}
                <div class="col-md-10-mb-3">
                    <div class="clearfix">
                        <p>
                        <a class="float-left" href=""><strong>{{comment.made_by|title}}</strong></a><br>
                        </p>
                        <p>{{comment.Content}}.</p>
                        <ul class="list-unstyled list-inline media-detail pull-right">
                            <li><i class="fa fa-calendar"></i>{{comment.Comment_Date}}</li>
                        </ul>
                    </div>
                </div>
                {% endfor %}
                </div>
            </div>
        </div>
    
</section>
</div>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    
    <div class="login-form">
        
        

        {% if message %}
        <div>{{ message }}</div>
        {% endif %}
        <form action="{% url 'auctions:login' %}" method="post">
            <h2 class="text-center">Sign In</h2>
            {% csrf_token %}
            <div class="form-group">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-group">
                <input class="btn btn-primary btn-block" type="submit" value="Login">
            </div>
        </form>
        <p class="text-center">Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a></p> 
    </div>
    

{% endblock %}

auctions/templates/auctions/new_bid.html
<!DOCTYPE html>
<!DOCTYPE html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <div class="form-group">
            <form action="{% url 'auctions:bid' listing_id%}" method="post">
                {% csrf_token %}
                    {{ form.as_p }}
                <div class="row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary float-right">Bid
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </body>
</html>

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <div class="login-form">

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        <h2 class="text-center">Sign Up</h2>
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <div class="form-group">
        <input class="btn btn-primary btn-block" type="submit" value="Register">
        </div>
    </form>

    <p class="text-center">Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a></p> 
</div>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}


{% block body %}

{% if no_item %}
<div class="centered">
    <h1>No item to display</h1>
</div>
{% else %}
<div class="centered">
    <h3>Watchlist</h3>
</div>
<section class="products">

    {% for listing in watched_list %}
        <div class="card mr-3 mb-3" style="width: 18rem;">
          <img class="card-img-top" src="{{listing.Product_Name.product_image_url}}" alt="Image not available">
          <div class="card-body">
            <h5 class="card-title">
              <a href="{% url 'auctions:listing_page' listing_id=listing.Product_Name.id%}">{{listing.Product_Name.product_name}}
              </a> 
            </h5>
            <p>Starting bid: {{listing.Product_Name.minimal_bid}} €</p>
            <p>Added at: {{listing.added_at}} </p>
            
          </div>
        </div>
      {% endfor %}
      </section>
{% endif %}
{% endblock %}